[workspace]
resolver = "2"
members = [
    "libs/common", "libs/blocks",
    "libs/db", "libs/messaging",
    "services/api",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
