# Dockerfile for webhook_service
FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package webhook_service

FROM debian:buster-slim
COPY --from=builder /app/target/release/webhook_service /usr/local/bin/webhook_service
CMD ["webhook_service"]
