# Dockerfile for timer_service
FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package timer_service

FROM debian:buster-slim
COPY --from=builder /app/target/release/timer_service /usr/local/bin/timer_service
CMD ["timer_service"]
