# Dockerfile for websocket_service
FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package websocket_service

FROM debian:buster-slim
COPY --from=builder /app/target/release/websocket_service /usr/local/bin/websocket_service
CMD ["websocket_service"]
