# Dockerfile for graph_processor_worker
FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package graph_processor_worker

FROM debian:buster-slim
COPY --from=builder /app/target/release/graph_processor_worker /usr/local/bin/graph_processor_worker
CMD ["graph_processor_worker"]
