# Dockerfile for rest_service
FROM rust:1.72 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package rest_service

FROM debian:buster-slim
COPY --from=builder /app/target/release/rest_service /usr/local/bin/rest_service
CMD ["rest_service"]
